name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, close]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
      - name: Check code formatting with Prettier
        run: npx prettier . --check

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
      - name: Run TypeScript compiler
        run: npx tsc --noEmit

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build

  deploy:
    name: Deploy
    needs: check-merge
      if: needs.check-merge.outputs.merged == 'true'
    uses: ./.github/workflows/auto_deploy.yml
    secrets: inherit
